version: '3.1'

services:
  backend:
    image: mms-backend
    container_name: mms-backend
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
  db:
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_DB: 'mms'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
    container_name: mms-db
    ports:
      - '5432:5432'
