version: '3.1'

services:
  db:
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_DB: 'mms'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
    container_name: mms-db
    ports:
      - '5432:5432'
