version: '3.1'

services:
  backend:
    image: mms-backend
    container_name: mms-backend
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: mms-db
      POSTGRES_PORT: 5432
      POSTGRES_USERNAME: root
      POSTGRES_PASSWORD: root
      JWT_EXPIRES_IN: 1h
      JWT_SECRET: secret
    ports:
      - '3000:3000'
  db:
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_DB: 'mms'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
    container_name: mms-db
    ports:
      - '5432:5432'
